export type Stop = { n: string; c: [number, number] };
export type DayMap = { c: [number, number]; z: number; s: Stop[] };

export const TRIP_START = new Date(2026, 8, 2);
export const getTripDay = () =>
  Math.floor((Date.now() - TRIP_START.getTime()) / 86400000) + 1;

export const OVERVIEW: DayMap = {
  c: [35.2, 137.6], z: 6,
  s: [
    { n: "Tokyo 1 (5N)", c: [35.690, 139.797] },
    { n: "Kamakura (Tagesausflug)", c: [35.319, 139.546] },
    { n: "Hakone/Gora (2N)", c: [35.241, 139.027] },
    { n: "Osaka (3N)", c: [34.668, 135.500] },
    { n: "Kyoto (5N)", c: [35.012, 135.768] },
    { n: "Hiroshima (Tagesausflug)", c: [34.395, 132.453] },
    { n: "Ito/Izu (2N)", c: [34.965, 139.099] },
    { n: "Tokyo 2 (2N)", c: [35.69, 139.7] },
  ],
};

export const DM: Record<number, DayMap> = {
  1:  { c: [35.61,139.78], z:11, s: [{ n:"Haneda Airport",c:[35.549,139.780]},{ n:"ATM + SIM + Suica (Terminal)",c:[35.549,139.780]},{ n:"Airbnb Chitose (Sumida)",c:[35.690,139.797]}]},
  2:  { c: [35.71,139.80], z:14, s: [{ n:"Senso-ji + Kaminarimon (frueh!)",c:[35.715,139.797]},{ n:"Asakusa Culture Center (8.OG Aussicht)",c:[35.711,139.796]},{ n:"Kappabashi (Messer-Strasse)",c:[35.713,139.788]},{ n:"Sumida River Park",c:[35.700,139.800]},{ n:"Tokyo Skytree (Sonnenuntergang!)",c:[35.710,139.811]}]},
  3:  { c: [35.690,139.700], z:14, s: [{ n:"Tokyo Metropolitan Building (Gratis-Aussicht)",c:[35.689,139.692]},{ n:"Omoide Yokocho (Memory Lane)",c:[35.693,139.699]},{ n:"Godzilla-Kopf (Gracery Hotel)",c:[35.695,139.702]},{ n:"Map Camera",c:[35.694,139.703]},{ n:"Shinjuku Gyoen (Garten) — 500 Y",c:[35.685,139.710]},{ n:"Isetan + Takashimaya Depachika",c:[35.690,139.703]}]},
  4:  { c: [35.665,139.702], z:14, s: [{ n:"Meiji-Schrein (frueh, Shinto-Wald)",c:[35.676,139.699]},{ n:"Takeshita/Harajuku + Omotesando",c:[35.670,139.706]},{ n:"Cat Street → Shibuya",c:[35.665,139.704]},{ n:"Shibuya Crossing + Hachiko",c:[35.659,139.700]},{ n:"Shibuya Sky (230m) — 2.500 Y",c:[35.658,139.702]},{ n:"Nintendo Tokyo (Parco)",c:[35.663,139.697]},{ n:"Daikanyama / Nakameguro",c:[35.644,139.699]}]},
  5:  { c: [35.68,139.78], z:13, s: [{ n:"Asakusa Anleger (Bootsstart)",c:[35.710,139.799]},{ n:"Tokyo Waterbus (Sumida-Fluss)",c:[35.685,139.785]},{ n:"Hamarikyu Gardens (Anleger im Garten) — 300 Y",c:[35.660,139.763]},{ n:"Ginza + Itoya + Uniqlo Flagship",c:[35.671,139.765]}]},
  6:  { c: [35.320,139.545], z:13, s: [{ n:"Kamakura Station",c:[35.319,139.550]},{ n:"Kotoku-in (Grosser Buddha) — 300 Y",c:[35.317,139.535]},{ n:"Yuigahama Strand",c:[35.300,139.550]},{ n:"Tsurugaoka Hachimangu",c:[35.325,139.556]}]},
  7:  { c: [35.45,139.25], z:10, s: [{ n:"Morishita (Start)",c:[35.690,139.797]},{ n:"Shinjuku (Romancecar)",c:[35.690,139.700]},{ n:"Hakone-Yumoto",c:[35.250,139.077]},{ n:"Ryokan Gora",c:[35.241,139.027]}]},
  8:  { c: [35.22,139.03], z:12, s: [{ n:"Hakone-Schrein (Torii im See)",c:[35.200,139.031]},{ n:"Owakudani Vulkan",c:[35.264,139.025]},{ n:"Togendai (Piratenschiff)",c:[35.232,139.013]},{ n:"Hakone-Machi (Ankunft Schiff)",c:[35.196,139.022]}]},
  9:  { c: [34.85,135.56], z:8,  s: [{ n:"Hakone-Yumoto (Abreise)",c:[35.250,139.077]},{ n:"Shin-Osaka (Ankunft)",c:[34.733,135.500]},{ n:"Airbnb Osaka",c:[34.668,135.500]},{ n:"Dotonbori (abends)",c:[34.668,135.502]}]},
  10: { c: [34.685,135.500], z:13, s: [{ n:"Dotonbori + Shinsaibashi-Arkade",c:[34.668,135.502]},{ n:"Naniwa Camera Shinsaibashi",c:[34.672,135.501]},{ n:"Umeda Sky Building (Sonnenuntergang) — 1.500 Y",c:[34.706,135.490]}]},
  11: { c: [34.695,135.510], z:13, s: [{ n:"Osaka Castle Park (frueh) — kostenlos",c:[34.687,135.526]},{ n:"Tenjinbashi-suji (laengste Arkade Japans)",c:[34.707,135.512]},{ n:"Nakazakicho (Kuenstler-Viertel)",c:[34.712,135.497]}]},
  12: { c: [34.85,135.62], z:10, s: [{ n:"Kuromon Ichiba Market (frueh!) — kostenlos",c:[34.666,135.506]},{ n:"Osaka Station (Abfahrt JR)",c:[34.702,135.496]},{ n:"Kyoto Station + Rihga Royal",c:[34.986,135.759]},{ n:"Kamo River Abend",c:[35.035,135.772]}]},
  13: { c: [34.70,134.30], z:8,  s: [{ n:"Kyoto Station (Shinkansen)",c:[34.986,135.759]},{ n:"Hiroshima Friedenspark + Atombombenkuppel — kostenlos",c:[34.395,132.453]},{ n:"Friedensmuseum — 200 Y",c:[34.391,132.452]},{ n:"Okonomiyaki Hiroshima-Stil",c:[34.393,132.456]}]},
  14: { c: [34.99,135.76], z:12, s: [{ n:"Fushimi Inari (frueh 6:30!) — kostenlos",c:[34.967,135.773]},{ n:"Kiyomizu-dera + Higashiyama — 500 Y",c:[34.994,135.785]},{ n:"Kinkaku-ji (Goldener Pavillon) — 500 Y",c:[35.039,135.729]},{ n:"Gion Abend",c:[35.003,135.778]}]},
  15: { c: [35.013,135.793], z:15, s: [{ n:"Philosophenweg (Kanal-Spazierweg) — kostenlos",c:[35.015,135.792]},{ n:"Honen-in (Moos, Reetdach) — kostenlos",c:[35.019,135.797]},{ n:"Eikando Tempelgarten — 600 Y",c:[35.012,135.796]},{ n:"Nanzen-ji + Aquadukt — kostenlos",c:[35.011,135.792]}]},
  16: { c: [35.010,135.710], z:11, s: [{ n:"Arashiyama: Saga Toriimoto (Edo-Strasse)",c:[35.023,135.665]},{ n:"Gio-ji Moosgarten — 500 Y",c:[35.022,135.661]},{ n:"Otagi Nenbutsuji (1.200 Statuen) — 300 Y",c:[35.028,135.658]},{ n:"Bambuswald — kostenlos",c:[35.016,135.671]},{ n:"Uji: Byodoin Tempel — 600 Y",c:[34.889,135.808]}]},
  17: { c: [34.99,139.06], z:9,  s: [{ n:"Kyoto Station (Shinkansen-Abfahrt)",c:[34.986,135.759]},{ n:"Atami Station (Umstieg)",c:[35.095,139.074]},{ n:"Ito Station (Izu Kyuko Linie)",c:[34.965,139.099]},{ n:"Ito Hafen/Fischmarkt",c:[34.965,139.101]}]},
  18: { c: [34.92,139.11], z:12, s: [{ n:"Jogasaki-Kueste: Kadowaki Haengebruecke — kostenlos",c:[34.892,139.126]},{ n:"Cliff Walk Jogasaki",c:[34.900,139.122]},{ n:"Ito Kogen (Bergplateau, Lunch)",c:[34.95,139.08]},{ n:"Ito Hafen (Austernbar)",c:[34.965,139.101]}]},
  19: { c: [35.30,139.20], z:8,  s: [{ n:"Ito Station (Abreise)",c:[34.965,139.099]},{ n:"Atami (Umstieg Shinkansen)",c:[35.095,139.074]},{ n:"TeamLab Planets (Ticket VORAB!) — 3.200 Y",c:[35.647,139.791]},{ n:"Tokyo 2 Airbnb",c:[35.690,139.700]}]},
  20: { c: [35.685,139.760], z:12, s: [{ n:"Kaiserpalast-Ostgaerten — kostenlos",c:[35.685,139.757]},{ n:"Tokyo Station / Marunouchi",c:[35.681,139.767]},{ n:"Ginza (Itoya, Uniqlo/GU Flagship)",c:[35.671,139.765]},{ n:"Ueno Park + Ameyoko",c:[35.715,139.773]},{ n:"Akihabara (Manga, Anime)",c:[35.698,139.773]}]},
  21: { c: [35.72,139.95], z:10, s: [{ n:"Tokio 2 Airbnb (entspannter Vormittag)",c:[35.690,139.700]},{ n:"Ueno (Keisei Skyliner Start)",c:[35.711,139.774]},{ n:"Narita Airport (Abflug 22:30)",c:[35.772,140.393]}]},
};

export type Day = {
  nr: number; datum: string; ort: string; strecke: string; hotel: string;
  top3: string[];
  ablauf: [string, string, string, string][];
  info: string[];
  foodtours?: { name: string; detail: string }[];
  ryokans?: { name: string; anreise: string; baby: string }[];
};

export const DAYS: Day[] = [
  { nr:1, datum:"Mi 2.9.", ort:"Tokio", strecke:"Haneda → Tokio", hotel:"Airbnb Chitose 3-8-6, Sumida (Morishita Station 3 Min.)",
    top3:["Ankunft Haneda 22:20 Uhr","ATM + SIM + Suica direkt am Flughafen (~8.500 Y / 47 €)","Taxi zum Hotel — ~4.000 Y (~22 €)"],
    ablauf:[
      ["22:20","Landung + Immigration + Gepaeck","~40 Min.","Wickelraum Terminal 2 vorhanden, auch nachts"],
      ["23:00","ATM (7-Eleven): 20.000 Y ziehen (~110 €)","10 Min.","Baby im Buggy; ATM Englisch verfuegbar"],
      ["23:10","SIM-Karte: IIJmio-Automat — 15 GB/30 Tage ca. 3.000 Y (~16 €)","10 Min.","Sofort einstecken, Netz aktiv"],
      ["23:20","Suica-Karte: Ticketautomat — 500 Y Kaution + 5.000 Y Guthaben (~30 €)","10 Min.","Suica = U-Bahn, JR, Bus, Konbini, Automaten"],
      ["23:40","Taxi zum Hotel — 3.500–6.000 Y (~19–33 €)","~30 Min.","Baby schlaeeft"],
      ["00:10","Airbnb Check-in (Chitose 3-8-6, Sumida)","20 Min.","Schluessel-Uebergabe oder Lockbox — vorab mit Host klaeren"],
      ["00:30+","Sofort schlafen!","—","Auch IHR habt Jetlag — Isabelle warnt: erster Tag ist hart!"],
    ],
    info:["Suica bei Heimreise: 500 Y Kaution + Restguthaben rueckerstattbar an jedem JR-Automaten","Asakusa Culture Center 8.OG: Kostenlos, keine Tickets noetig, Mo–So 9–21 Uhr","Naechster Bahnhof: Morishita Station (Toei Shinjuku + Oedo Linie), 3 Min. Fussweg"]},

  { nr:2, datum:"Do 3.9.", ort:"Tokio", strecke:"Asakusa + Skytree", hotel:"Airbnb Chitose 3-8-6, Sumida (Morishita Station 3 Min.)",
    top3:["Asakusa komplett: Senso-ji, Nakamise, Kaminarimon, Sumida Park — kostenlos","Tokyo Skytree (634m) zum Sonnenuntergang — Ticket VORAB, ~3.100 Y (~17 €)","Voller aktiver Tag — Asakusa zu Fuss, dann Skytree"],
    ablauf:[
      ["07:00–08:00","Fruehstueck Airbnb (Kueche nutzen)","60 Min.","Baby wacht jetlag-bedingt frueh — passt"],
      ["08:00–08:20","Toei Oedo: Morishita → Kuramae + 8 Min. Fussweg nach Asakusa","20 Min.","BABY SCHLAEFT IM BUGGY: Kurzschlaf im Zug"],
      ["08:20–09:30","Senso-ji + Kaminarimon-Tor FRUEH (kaum Touristen vor 9:30!) — kostenlos","70 Min.","Frueh = magische Stimmung, leere Gassen, beste Fotos (Tipp Michelle)"],
      ["09:30–10:30","Nakamise-Strasse (Souvenirs, Street Food) + Asakusa Culture Center 8.OG (Gratis-Aussicht) — kostenlos","60 Min.","Aufzug ins 8.OG, 360-Grad-Blick auf Senso-ji + Skytree"],
      ["10:30–11:30","Sumida River Park Spaziergang (Skytree-Blick ueber den Fluss) — kostenlos","60 Min.","Schoene Promenade, Buggy ideal; Fotomotiv Skytree + Asahi-Gebaeude"],
      ["11:30–12:30","Kappabashi (Kuechenmesser- und Geschirr-Strasse, Foodie-Paradies) — kostenlos","60 Min.","10 Min. von Senso-ji; beruehmte Messer, Sampuru (Plastik-Food); tolle Mitbringsel"],
      ["12:30–13:30","Mittagessen Asakusa: Tempura oder Sushi (Tradition) — ~1.500–2.500 Y","60 Min.","Asakusa ist beruehmt fuer alteingesessene Tempura-Lokale"],
      ["13:30–15:00","Heimfahrt + Baby-Mittagsschlaf Airbnb (oder Buggy)","90 Min.","BABY SCHLAEFT IM BUGGY: laengerer Mittagsschlaf; ihr ladet auch durch"],
      ["15:00–15:30","Toei Oedo/Asakusa Linie zum Skytree (Oshiage)","30 Min.","BABY SCHLAEFT IM BUGGY: Kurzschlaf"],
      ["15:30–17:00","Tokyo Skytree (634m): Aussichtsdeck — Ticket vorab ~3.100 Y","90 Min.","Nachmittags rein, dann oben bleiben; ab Tembo Deck spektakulaer"],
      ["17:00–18:30","Sonnenuntergang vom Skytree (Lena: vor dem Slot rein, laenger bleiben!)","90 Min.","Goldene Stunde + Lichtermeer Tokios; Baby liebt die Hoehe + Lichter"],
      ["18:30–20:00","Dinner Solamachi (Skytree-Mall, viele Restaurants) — ~1.500–2.500 Y","90 Min.","Direkt im Skytree-Komplex; entspannt, Hochstuhl vorhanden"],
      ["20:00–20:40","Heimfahrt zur Unterkunft (Oshiage → Morishita)","40 Min.","BABY SCHLAEFT IM BUGGY"],
    ],
    info:["Skytree-Tickets vorab online (Fast Skytree Ticket spart Wartezeit); Sonnenuntergangszeit Anfang Sept ~18:00 Uhr","Asakusa + Skytree liegen nah beieinander — idealer kombinierter Tag, beide oestlich nahe eurer Unterkunft","Kappabashi-Tipp: zwischen Asakusa und Ueno; japanische Kuechenmesser sind weltklasse + guenstig"]},

  { nr:3, datum:"Fr 4.9.", ort:"Tokio", strecke:"Shinjuku komplett", hotel:"Airbnb Chitose 3-8-6, Sumida (Morishita Station 3 Min.)",
    top3:["Tokyo Metropolitan Government Building (kostenlose Aussicht, 202m) + Omoide Yokocho","Map Camera (Gebrauchtkameras) + Godzilla-Kopf am Gracery Hotel","Shinjuku Gyoen Garten + Isetan & Takashimaya Depachika"],
    ablauf:[
      ["07:30–08:30","Fruehstueck Airbnb","60 Min.","Reisepass mit fuer Map Camera (Steuerfrei)!"],
      ["08:30–09:00","Toei Shinjuku Linie: Morishita → Shinjuku DIREKT (~280 Y)","30 Min.","BABY SCHLAEFT IM BUGGY: Kurzschlaf — Direktlinie!"],
      ["09:00–10:00","Tokyo Metropolitan Government Building: kostenlose Aussicht 45. Stock (202m) — kostenlos","60 Min.","Oeffnet 9:30; bei klarem Wetter bis Fuji; gratis Alternative zu Skytree/Shibuya Sky"],
      ["10:00–10:45","Omoide Yokocho ('Memory Lane', nostalgische Yakitori-Gassen) — kostenlos","45 Min.","Tagsueber ruhig + fotogen (abends voll/verraucht); Nachkriegs-Tokio-Flair"],
      ["10:45–11:15","Godzilla-Kopf am Shinjuku Gracery Hotel (Kabukicho-Rand) — kostenlos","30 Min.","Riesiger Godzilla-Kopf ueber dem Hotel; lustiges Fotomotiv; Kabukicho tagsueber harmlos"],
      ["11:15–12:45","Map Camera Shinjuku (6 Etagen Gebrauchtkameras) — kein Eintritt","90 Min.","Steuerfrei mit Reisepass ab 5.000 Y; Voigtlaender, Leica, Fuji; klimatisiert"],
      ["12:45–13:45","Mittagessen Shinjuku — ~1.200–2.000 Y","60 Min.",""],
      ["13:45–14:15","Fussweg/U-Bahn zu Shinjuku Gyoen","30 Min.","BABY SCHLAEFT IM BUGGY: Mittagsschlaf beginnt"],
      ["14:15–16:00","Shinjuku Gyoen (einer der schoensten Gaerten Tokios, 58ha) — 500 Y","105 Min.","BABY SCHLAEFT IM BUGGY weiter; riesig, ruhig, perfekt fuer Buggy; jap.+engl.+franz. Garten"],
      ["16:00–18:00","Isetan + Takashimaya Department Stores (Depachika Food-Hallen) — kostenlos/Shopping","120 Min.","Zwei legendaere Kaufhaeuser; Depachika im UG zum Schlemmen; Tax-Free mit Reisepass"],
      ["18:00–19:00","Dinner Depachika oder Shinjuku-Restaurant — ~1.500–2.500 Y","60 Min.",""],
      ["19:00–19:40","Toei Shinjuku Linie: Shinjuku → Morishita DIREKT","40 Min.","BABY SCHLAEFT IM BUGGY"],
    ],
    info:["Metropolitan Building: kostenlose Aussicht, oft uebersehen; entspannter Vormittagsstart","Map Camera: Nishi-Shinjuku 1-12-5; 10–15% guenstiger als BIC/Yodobashi; Steuerfrei mit Reisepass","Shinjuku Gyoen: einer der gepflegtesten Gaerten Tokios; Eintritt 500 Y lohnt sich; viel Schatten","Isetan Shinjuku gilt als bestes Depachika Tokios — Dutzende Counter, Bento, Sushi, Patisserie"]},

  { nr:4, datum:"Sa 5.9.", ort:"Tokio", strecke:"Harajuku + Shibuya", hotel:"Airbnb Chitose 3-8-6, Sumida (Morishita Station 3 Min.)",
    top3:["Meiji-Schrein (Shinto-Wald) + Takeshita/Harajuku + Omotesando + Cat Street","Shibuya Crossing + Shibuya Sky (230m) + Nintendo Tokyo (Parco)","Daikanyama + Nakameguro am Nachmittag (ruhiger Gegenpol)"],
    ablauf:[
      ["07:30–08:00","Fruehstueck Airbnb","30 Min.",""],
      ["08:00–08:40","JR Yamanote bis Harajuku (~1 Umstieg, ~300 Y)","40 Min.","BABY SCHLAEFT IM BUGGY: Kurzschlaf"],
      ["08:40–10:00","Meiji-Schrein FRUEH (175ha Wald, ruhig am Morgen) — kostenlos","80 Min.","Frueh = fast leer, mystisch; schattiger Waldweg; Buggy ok"],
      ["10:00–11:00","Takeshita-Street + Harajuku (Jugendkultur, Crepes, bunt) — kostenlos","60 Min.","Eng + lebhaft; ikonische Tokio-Energie; Crepe probieren"],
      ["11:00–12:00","Omotesando (Luxus-Allee, Tadao-Ando-Architektur) + Cat Street zu Fuss Richtung Shibuya — kostenlos","60 Min.","Cat Street verbindet Harajuku + Shibuya zu Fuss; Boutiquen, fotogen"],
      ["12:00–13:00","Mittagessen Shibuya — ~1.500–2.500 Y","60 Min.","Riesige Auswahl; viele Lokale mit Hochstuhl"],
      ["13:00–14:30","Baby-Mittagsschlaf: Cafe-Pause oder Miyashita Park (Rooftop) — kostenlos","90 Min.","BABY SCHLAEFT IM BUGGY: Mittagsschlaf; gruenes Mall-Dach mit Cafes"],
      ["14:30–15:00","Shibuya Crossing + Hachiko-Statue + Center Gai — kostenlos","30 Min.","Beruehmteste Kreuzung der Welt; Hachiko-Foto"],
      ["15:00–16:00","Shibuya Sky (230m, Open-Air-Dachterrasse) — Ticket vorab ~2.500 Y","60 Min.","Spektakulaere 360-Grad-Sicht; bei klarem Wetter Fuji; nachmittags/Sonnenuntergang ideal"],
      ["16:00–17:00","Nintendo Tokyo + Pokemon Center (Shibuya Parco, 6. Stock) — kostenlos/Shopping","60 Min.","Erster offizieller Nintendo-Store Japans; Mario, Zelda, Splatoon-Merch; nebenan Pokemon + Jump Shop"],
      ["17:00–18:30","Daikanyama (Tsutaya Books) ODER Nakameguro (Meguro-Kanal, Cafes) — kostenlos","90 Min.","Ruhiger Gegenpol zum lauten Shibuya; stylish, kaum Touristen; Cafe am Kanal"],
      ["18:30–20:00","Dinner Shibuya/Nakameguro — ~2.000–3.000 Y","90 Min.","Optional: Shibuya Crossing bei Neon auf dem Rueckweg"],
      ["20:00–20:45","Heimfahrt zur Unterkunft","45 Min.","BABY SCHLAEFT IM BUGGY"],
    ],
    info:["Harajuku + Shibuya liegen direkt nebeneinander (Cat Street verbindet sie zu Fuss) — idealer kombinierter Tag","Shibuya Sky: Tickets unbedingt vorab (Sonnenuntergang-Slots schnell weg); Open-Air-Dach ist das Highlight","Nintendo Tokyo (Parco): erster offizieller Store Japans; oft Wartezeit am WE — frueh dran sein","Kostenlose Crossing-Aussicht alternativ: Mexikaner (Cielito Lindo, Q Front) oder Starbucks ueber der Kreuzung"]},

  { nr:5, datum:"So 6.9.", ort:"Tokio", strecke:"Bootsfahrt + Hamarikyu + Ginza", hotel:"Airbnb Chitose 3-8-6, Sumida (Morishita Station 3 Min.)",
    top3:["Tokyo Waterbus: Bootsfahrt Asakusa → Hamarikyu ueber den Sumida — ~1.200 Y","Hamarikyu Gardens (400-J. Kaisergarten am Wasser) — 300 Y","Ginza Boulevard + Kamakura-Vorbereitung"],
    ablauf:[
      ["08:00–08:45","Fruehstueck Airbnb","45 Min.",""],
      ["08:45–09:10","Toei Oedo: Morishita → Kuramae, Fussweg zum Asakusa-Anleger","25 Min.","BABY SCHLAEFT IM BUGGY: Kurzschlaf"],
      ["09:30–10:10","Tokyo Waterbus Asakusa → Hamarikyu (Sumida-Fluss, ~40 Min.) — ~1.200 Y","40 Min.","DEINE BOOTSFAHRT! Unter 12 Bruecken durch; Skytree + Skyline vom Wasser; Baby liebt Schiff"],
      ["10:10–12:00","Hamarikyu Gardens (Anleger IM Garten!) — 300 Y","110 Min.","Boot legt direkt im Garten an; Kaisergarten, Teehaus auf dem Teich (Matcha ~510 Y)"],
      ["12:00–12:30","Fussweg/U-Bahn Hamarikyu → Ginza","30 Min.",""],
      ["12:30–14:00","Ginza: Mittagessen + Ginza Six / Depachika (klimatisiert) — ~1.500–2.500 Y","90 Min.","HITZE-SCHUTZ: Mittagshitze in klimatisierten Kaufhaeusern; Ginza Six Dachgarten"],
      ["14:00–15:30","Ginza-Bummel: Itoya (12-Etagen-Schreibwaren!), Uniqlo/GU Flagship — kostenlos","90 Min.","Itoya = legendaeres Papier-/Schreibwarenkaufhaus; Uniqlo Ginza groesste Filiale; Tax-Free"],
      ["15:30–16:00","U-Bahn zurueck — BABY SCHLAEFT IM BUGGY (spaeter Mittagsschlaf)","30 Min.",""],
      ["16:00–17:30","Kamakura vorbereiten: Suica aufladen, Karte offline, Rucksack packen","90 Min.","Packliste: Windeln extra, Sonnenschutz, Wasser, Babytrage, ggf. Badekleidung"],
      ["18:00–20:00","Dinner nahe Unterkunft + Baby-Routine","120 Min.","Morgen frueh Aufbruch nach Kamakura!"],
    ],
    info:["Tokyo Waterbus (Himiko/Emeraldas-Boote): Asakusa → Hamarikyu, fahrplan unter tokyo-park.or.jp/water; Anleger direkt im Garten — kein extra Weg!","Hamarikyu Teehaus: Matcha + Wagashi auf einer Insel im Teich, sehr besonders","Itoya Ginza: 12 Etagen Papier, Stifte, Kalligrafie — Geheimtipp fuer schoene Mitbringsel"]},

  { nr:6, datum:"Mo 7.9.", ort:"Kamakura", strecke:"Tokio → Tokio", hotel:"Airbnb Chitose 3-8-6, Sumida (Morishita Station 3 Min.)",
    top3:["Kotoku-in Grosser Buddha (13m Bronze, 1252, UNESCO) — 300 Y","Yuigahama Strand (Sandstrand, Baby im Sand)","Tsurugaoka Hachimangu (Shinto-Schrein 1063) — kostenlos"],
    ablauf:[
      ["07:30–09:00","Fruehstueck, Baby fertig, Rucksack","90 Min.",""],
      ["09:15–10:15","Zug JR Yokosuka → Kamakura — ~950 Y/Person","60 Min.","BABY SCHLAEFT IM BUGGY: Kurzschlaf"],
      ["10:30–11:15","Kotoku-in: Grosser Buddha (1252 n.Chr.) — 300 Y","45 Min.","Kinderwagen bis Eingang ok"],
      ["11:15–12:00","Yuigahama Strand (VOR der Mittagshitze!) — kostenlos","45 Min.","Baby im Sand; Meeresbrise; danach raus aus der Sonne"],
      ["12:00–13:30","Mittagessen Kamakura drinnen/klimatisiert (Soba) — ~1.000 Y","90 Min.","HITZE-SCHUTZ: 12–14 Uhr bewusst im Schatten/klimatisiert (Tipp Melly-Freundin)"],
      ["13:30–15:00","Zug zurueck nach Tokyo — ~950 Y","60 Min.","BABY SCHLAEFT IM BUGGY: Mittagsschlaf!"],
      ["15:00–17:30","Hotel, Eure Ruhe","150 Min.",""],
      ["17:30–20:00","Letzter Tokio-Abend + Dinner","150 Min.","Morgen Hakone-Abreise!"],
    ],
    info:["Tsurugaoka Hachimangu: bedeutendster Shinto-Schrein Kamakuras, kostenlos; lohnt wenn Zeit nach Buddha","Kamakura Quick-Option: Nur Buddha + Lunch + Strand = entspannte 3–4 Std."]},

  { nr:7, datum:"Di 8.9.", ort:"Hakone", strecke:"Tokio → Hakone", hotel:"Ryokan Gora (TBD)",
    top3:["Odakyu Romancecar (Panorama-Luxuszug) — ~1.400 Y/Person gesamt (~7,50 €)","Hakone-Tozan-Bahn (1919, 3 Spitzkehren) — im Freepass","Kaiseki-Dinner + Onsen Nacht 1 (im Ryokanpreis enthalten!)"],
    ablauf:[
      ["07:00–08:00","Fruehstueck Airbnb (Kueche nutzen)","60 Min.","Gepaeck per Takkyubin vorausschicken — ~1.500 Y/Koffer"],
      ["09:00–09:30","Toei Shinjuku Linie: Morishita → Shinjuku DIREKT (~30 Min., ~280 Y)","30 Min.","BABY SCHLAEFT IM BUGGY: Direktlinie — ideal fuer Hakone-Abfahrt!"],
      ["10:00–11:20","Romancecar Shinjuku → Hakone-Yumoto — ~1.400 Y/Person","80 Min.","Panoramafenster, breite Sitze; Baby schlaeeft"],
      ["11:20–12:00","Hakone-Yumoto: Onsen Manju probieren (~200 Y) + Pause","40 Min.","Wickelraum am Bahnhof"],
      ["12:00–12:40","Tozan-Bahn → Gora (3 Spitzkehren, 1919!) — im Freepass","40 Min.","Faszinierend"],
      ["12:40–15:00","Gora Park (550 Y) + Check-in vorbereiten","135 Min.","Check-in meist ab 15 Uhr"],
      ["15:00–16:30","Check-in Ryokan + Baby-Mittagsschlaf","90 Min.","Futon bodennah — ideal fuer Baby"],
      ["16:30–17:30","Erste Onsen-Session (privater Raum im Ryokan!)","60 Min.","Onsen = im selben Gebaeude; Babytauglichkeit vorab klaeren"],
      ["17:30–19:00","Kaiseki-Dinner Nacht 1 (im Preis enthalten)","90 Min.","Bei Check-in: Uhrzeit + Allergien angeben"],
    ],
    info:["Romancecar vorab buchen: odakyu.jp (Sitzplatzreservierung ~800 Y Aufpreis)","Hakone Freepass 3-Tage: ~5.600 Y (~30 €) — spart ~2.000–3.000 Y/Person, deckelt alle Transporte","Onsen im Ryokan = privater Baderaum im selben Haus — kein Ausgehen noetig","Kaiseki: Meistens 8–12 Gaenge, im Zimmer oder Privatraum, kein extra Buchen noetig"],
    ryokans:[
      {name:"Yunosumika (Nr. 1 Empfehlung)",anreise:"Kabelbahn Gora → Naka-Gora, 5 Min. Fussweg",baby:"Babybett-Verleih, Spielzeug, Baby-Menu auf Anfrage"},
      {name:"Toki no Yu Setsugetsuka",anreise:"Direkt gegenueber Gora Station",baby:"Familienzimmer bis 4 Pers., privates Onsen"},
      {name:"Ajisai Onsen Ryokan",anreise:"~15 Min. Fussweg oder Taxi",baby:"3 private Onsen-Raeume buchbar, Spielzeug, 32m2 Familienstudio"},
    ]},

  { nr:8, datum:"Mi 9.9.", ort:"Hakone", strecke:"Hakone → Hakone", hotel:"Ryokan Gora (TBD)",
    top3:["Hakone-Schrein VOR 8 Uhr (Torii im See — ab 9 Uhr Stunden Wartezeit!) — kostenlos","Owakudani Vulkan + schwarze Eier — im Freepass; Eier ~500 Y","Piratenschiff Lake Ashi — im Freepass"],
    ablauf:[
      ["06:30–07:00","Hakone-Schrein VOR 8 Uhr — kostenlos","30 Min.","Ab Vormittag 2–3 Std. Wartezeit; frueh = perfekte Fotos"],
      ["07:00–08:00","Fruehstueck Ryokan (inkl.)","60 Min.",""],
      ["09:00–09:30","Bus Gora → Hakone-Yumoto — im Freepass","30 Min.","BABY SCHLAEFT IM BUGGY: Kurzschlaf"],
      ["09:30–10:30","Kabelbahn Gora → Owakudani (via Sounzan) — im Freepass","60 Min.","Tolle Aussicht"],
      ["10:30–11:15","Owakudani Vulkan + schwarze Eier (~500 Y fuer 5 Stueck)","45 Min.","Schwefelgeruch intensiv — kurz halten; Eier heiss lassen"],
      ["11:15–12:30","Seilbahn → Togendai + Piratenschiff → Hakone-machi (45 Min.) — im Freepass","75 Min.","Baby liebt Schiff; schaukelt sanft"],
      ["12:30–13:30","Mittagessen Hakone-machi + Baby fuettern","60 Min.",""],
      ["13:30–14:30","Bus zurueck Gora — im Freepass","60 Min.","BABY SCHLAEFT IM BUGGY: Mittagsschlaf"],
      ["14:30–16:30","Baby Mittagsschlaf Ryokan (falls noetig) + Ruhe","120 Min.",""],
      ["16:30–17:30","Letzte Onsen-Session (Abschied vom Ryokan!)","60 Min.",""],
      ["17:30–19:00","Kaiseki-Dinner Nacht 2 (letzter Ryokan-Abend, im Preis enthalten)","90 Min.","Morgen frueh weiter nach Osaka — Koffer heute Abend packen"],
    ],
    info:["Mittwoch ideal: Seilbahn am WE = 1,5–2 Std. Wartezeit, wochentags kaum","Alte Tokaido-Strasse (optional): hist. Zedernweg ~1 Std.; Babytrage statt Buggy","Hakone Open-Air-Museum (optional): Skulpturen, Fussbad 1.600 Y — eigenes Handtuch","Hakone jetzt nur noch 2 Naechte (Atami entfaellt — wird durch Izu/Ito am Ende der Reise abgedeckt)"]},

  { nr:9, datum:"Do 10.9.", ort:"Osaka", strecke:"Hakone → Osaka", hotel:"Airbnb Osaka (gebucht ✓)",
    top3:["Morgen-Onsen letzter Slot im Ryokan","Shinkansen Odawara → Shin-Osaka — ~8.500 Y/Person (~46 €)","Abend: Erste Osaka-Eindruecke + Dotonbori bei Nacht"],
    ablauf:[
      ["07:00–07:30","Morgen-Onsen letzter Slot","30 Min.",""],
      ["07:30–08:30","Fruehstueck Ryokan (letztes Mal!)","60 Min.",""],
      ["09:00–09:45","Checkout + Tozan-Bahn Gora → Odawara","45 Min.",""],
      ["10:15–12:30","Shinkansen Odawara → Shin-Osaka — ~8.500 Y/Person","135 Min.","BABY SCHLAEFT IM BUGGY: Mittagsschlaf; Fensterplatz rechts fuer Fuji-Chance"],
      ["13:00–14:00","Ankunft Shin-Osaka, U-Bahn zum Airbnb — ~270 Y","60 Min.",""],
      ["14:00–16:00","Check-in Airbnb (3 Min. zum Bahnhof, Namba 3 Min.) + Baby-Mittagsschlaf","120 Min.","Babybett bestaetigt?"],
      ["16:00–18:00","Hotelumgebung erkunden: Shinsaibashi/Namba 3 Min. zu Fuss","120 Min.","Erste Eindruecke; kein Programm-Stress"],
      ["18:00–20:30","Dinner + Dotonbori bei Nacht (Glico-Mann, Neonlichter) — Street Food ~500–1.500 Y","150 Min.","Dotonbori abends am schoensten; Takoyaki, Okonomiyaki, Kushikatsu"],
    ],
    info:["Osaka = Foodie-Hauptstadt Japans; entspannter und lustiger als Tokyo","Airbnb 10.–13.9. (3 Naechte) — bestaetigt ✓","Dotonbori gleich am Ankunftsabend mitnehmen, da Osaka jetzt nur 3 Naechte hat"]},

  { nr:10, datum:"Fr 11.9.", ort:"Osaka", strecke:"Osaka → Osaka", hotel:"Airbnb Osaka (gebucht ✓)",
    top3:["Dotonbori bei Tag + Naniwa Camera (Gebrauchtkameras) — kein Eintritt","Street Food Namba: Takoyaki, Kushikatsu — ~500–2.000 Y","Umeda Sky Building zum Sonnenuntergang — 1.500 Y (~8 €)"],
    ablauf:[
      ["08:00–09:00","Fruehstueck Airbnb","60 Min.",""],
      ["09:00–09:30","U-Bahn zu Namba — ~230 Y","30 Min.","BABY SCHLAEFT IM BUGGY: Kurzschlaf"],
      ["09:30–11:00","Dotonbori bei Tag + Kanal + Shinsaibashi-Arkade (ueberdacht) — kostenlos","90 Min.","HITZE-SCHUTZ: ueberdachte Arkade bei Hitze; Baby wach"],
      ["11:00–12:00","Naniwa Camera Shinsaibashi — kein Eintritt","60 Min.","Voigtlaender, Contax, Fuji; Reisepass fuer 10% Steuerrabatt"],
      ["12:00–13:00","Street-Food-Lunch Namba (Takoyaki, Kushikatsu) — ~1.000–1.500 Y","60 Min.",""],
      ["13:00–14:30","U-Bahn zurueck — BABY SCHLAEFT IM BUGGY (Mittagsschlaf)","90 Min.",""],
      ["14:30–16:30","Baby Mittagsschlaf + Ruhe","120 Min.",""],
      ["16:30–18:30","Umeda Sky Building zum Sonnenuntergang — 1.500 Y","120 Min.","Floating Garden 173m; abends spektakulaer; Fahrstuhl vorhanden"],
      ["18:30–20:00","Dinner Umeda/Grand Front — ~2.000 Y","90 Min.",""],
    ],
    info:["Naniwa Camera: beste Gebrauchtkamera-Adresse Kansais, 5 Min. von Dotonbori","Umeda Sky Building: einer der imposantesten Wolkenkratzer Japans, Sonnenuntergang besonders schoen","Loewenkopf-Schrein + Castle Museum laut Lena nicht zwingend — ausgelassen"]},

  { nr:11, datum:"Sa 12.9.", ort:"Osaka", strecke:"Osaka → Osaka", hotel:"Airbnb Osaka (gebucht ✓)",
    top3:["Osaka Castle Park (kuehler Morgen) — kostenlos","Tenjinbashi-suji (Japans laengste Einkaufsstrasse) — kostenlos","Nakazakicho (Kuenstler-Viertel, Cafes) — kostenlos"],
    ablauf:[
      ["08:00–09:00","Fruehstueck Airbnb","60 Min.",""],
      ["09:00–09:30","U-Bahn zum Osaka Castle Park — ~230 Y","30 Min.","BABY SCHLAEFT IM BUGGY"],
      ["09:30–11:00","Osaka Castle Park (kuehler Morgen!) — Park kostenlos, Museum optional","90 Min.","Exponierter Park bewusst frueh, bevor die Sonne brennt; Buggy ideal"],
      ["11:00–12:30","Tenjinbashi-suji (Japans laengste Einkaufsstrasse, 2,6 km, ueberdacht) — kostenlos","90 Min.","HITZE-SCHUTZ: ueberdachte Arkade fuer Mittagshitze; viel lokales Leben"],
      ["12:30–13:30","Mittagessen Arkade (klimatisiert) — ~1.500 Y","60 Min.",""],
      ["13:00–14:30","U-Bahn zurueck — BABY SCHLAEFT IM BUGGY (Mittagsschlaf)","90 Min.",""],
      ["14:30–16:30","Baby Mittagsschlaf + Ruhe","120 Min.",""],
      ["16:30–18:30","Nakazakicho (Kuenstler-Viertel, Retro-Cafes) — kostenlos","120 Min.","Ruhig, kreativ; Cafe ideal zum Fuettern; fusslaeufig von Umeda"],
      ["18:30–20:00","Letzter Osaka-Abend: Abschluss-Dinner — ~2.000–3.500 Y","90 Min.","Koffer packen — morgen frueh Kuromon + weiter nach Kyoto"],
    ],
    info:["Nakazakicho: Osaks bekanntestes Kuenstler-Viertel, fusslaeufig von Umeda","Option: Minoh Park (40 Min. per Hankyu, ~400 Y) — Bergwald, Wasserfall","Lena: 3 Osaka-Naechte reichen vollkommen — Stadt ist schrill, schnell durch"]},

  { nr:12, datum:"So 13.9.", ort:"Kyoto", strecke:"Osaka → Kyoto", hotel:"Rihga Royal Hotel Kyoto (Anruf noetig!)",
    top3:["Kuromon Ichiba Market FRUEH (9 Uhr, vor den Massen!) — kostenlos, essen ~1.000 Y","JR Osaka → Kyoto (28 Min.) — ~580 Y/Person (~3,20 €)","Kamo River Abend (Demachiyanagi, Schildkroetensteine) — kostenlos"],
    ablauf:[
      ["07:30–08:30","Fruehstueck Airbnb + Koffer fertig","60 Min.",""],
      ["08:30–09:00","U-Bahn zu Kuromon Ichiba — ~230 Y","30 Min.","BABY SCHLAEFT IM BUGGY: Kurzschlaf"],
      ["09:00–10:30","Kuromon Ichiba Market FRUEH (130 Staende, frisch, kaum Touristen) — kostenlos","90 Min.","Markt oeffnet ~9 Uhr — frueh = volle Auswahl, Staende bauen auf; Tintenfisch, Sushi, Obst direkt essen"],
      ["10:30–11:30","Zurueck zum Airbnb, Gepaeck holen, Checkout","60 Min.",""],
      ["11:30–12:00","JR Osaka → Kyoto — ~580 Y/Person","30 Min.","BABY SCHLAEFT IM BUGGY: Kurzschlaf"],
      ["12:00–15:00","Ankunft Kyoto, Check-in Rihga Royal (Gepaeck abgeben) + Baby-Mittagsschlaf","180 Min.","Check-in ab 15 Uhr; Gepaeck vorher abgeben"],
      ["15:00–16:30","Kyoto Bahnhof (modernes Wahrzeichen, 11.OG gratis Aussicht)","90 Min.","Glas-Architektur; babytauglich"],
      ["16:30–18:30","Kamo River Abend: Demachiyanagi-Spaziergang, Schildkroetensteine — kostenlos","120 Min.","BABY SCHLAEFT IM BUGGY: Abendspaziergang; Einheimische sitzen am Fluss"],
      ["18:30–20:00","Dinner Pontocho oder Kamo River nahe Restaurants — ~2.000–4.000 Y","90 Min.",""],
    ],
    info:["Kuromon Markt frueh am Abreisetag = perfekt: vor den Massen, passt ins Baby-Frueh-Fenster","Kamo River = Kyotos Herzader; perfekter erster Eindruck; Einheimische mit Dango + Bier","WICHTIG: Rihga Royal Check-in muss jetzt auf 13.9. geaendert werden (nicht 14.9. — Osaka endet einen weiteren Tag frueher!)"]},

  { nr:13, datum:"Mo 14.9.", ort:"Hiroshima", strecke:"Kyoto → Hiroshima → Kyoto", hotel:"Rihga Royal Hotel Kyoto",
    top3:["Shinkansen Kyoto → Hiroshima (~1h 45min) — ~11.000 Y/Person (Hin+Rueck ~22.000 Y)","Friedenspark + Atombombenkuppel (UNESCO, Mahnmal) — kostenlos","Friedensmuseum — 200 Y (~1,10 €)"],
    ablauf:[
      ["06:30–07:00","Rihga Royal Fruehstueck frueh (inkl.) + Tagesrucksack","30 Min.","Langer Transit-Tag — frueh starten lohnt sich"],
      ["07:00–07:30","Zu Kyoto Station","30 Min.","BABY SCHLAEFT IM BUGGY: Kurzschlaf"],
      ["07:45–09:30","Shinkansen Kyoto → Hiroshima (Nozomi/Sakura) — ~11.000 Y/Person","105 Min.","BABY SCHLAEFT IM BUGGY: Langschlaf moeglich; reservierter Sitz"],
      ["09:30–10:00","Tram Hiroshima Station → Friedenspark (~15 Min.) — ~200 Y","30 Min.",""],
      ["10:00–11:30","Friedenspark + Atombombenkuppel (Genbaku Dome, UNESCO) — kostenlos","90 Min.","Weitlaeufig, Buggy ok; Mahnmal, Friedensglocke, Kinderdenkmal"],
      ["11:30–12:30","Friedensmuseum (Peace Memorial Museum) — 200 Y","60 Min.","Eindringlich; mit Baby in Trage; ggf. abwechselnd besuchen"],
      ["12:30–13:30","Mittagessen Hiroshima: Okonomiyaki Hiroshima-Stil (mit Nudeln!) — ~1.000 Y","60 Min.","Hiroshima-Okonomiyaki ist anders als Osaka — Spezialitaet!"],
      ["13:30–14:00","Tram zurueck zur Station","30 Min.","BABY SCHLAEFT IM BUGGY: Mittagsschlaf beginnt"],
      ["14:24–16:10","Shinkansen Hiroshima → Kyoto — ~11.000 Y/Person","105 Min.","BABY SCHLAEFT IM BUGGY: Mittagsschlaf im Zug"],
      ["16:30–17:30","Zurueck Rihga Royal, Pause","60 Min.",""],
      ["18:00–19:30","Entspanntes Dinner nahe Hotel — ~2.000 Y","90 Min.","Nach langem Tag bewusst ruhig"],
    ],
    info:["Bewusste Entscheidung: nur Hiroshima City + Friedensdenkmal, KEIN Miyajima (sonst 5,5 Std. Transit statt 3,5)","Langer Transit-Tag (~3,5 Std. Bahn) — fruehe Abfahrt + Baby-Schlaf im Shinkansen machen es machbar","Hiroshima-Okonomiyaki: mit Nudeln geschichtet, anders als Osaka-Variante — unbedingt probieren","Shinkansen-Kosten Hiroshima Hin+Rueck: ~22.000 Y/Person (~120 €) — der teuerste Tag der Reise"]},

  { nr:14, datum:"Di 15.9.", ort:"Kyoto", strecke:"Kyoto → Kyoto", hotel:"Rihga Royal Hotel Kyoto",
    top3:["Fushimi Inari ab 6:30 Uhr (vor den Massen!) — kostenlos","Kiyomizu-dera + Higashiyama-Gassen — 500 Y","Kinkaku-ji (Goldener Pavillon) — 500 Y"],
    ablauf:[
      ["06:00–06:30","U-Bahn Inari Station — ~230 Y","30 Min.","BABY SCHLAEFT IM BUGGY: Fruehzug"],
      ["06:30–08:30","Fushimi Inari Taisha (1.000+ Torii-Tore) — kostenlos","120 Min.","Frueh = Nebel, Waldstille, fast allein; je hoeher desto ruhiger; Babytrage oben"],
      ["08:30–09:00","U-Bahn/Bus Fushimi → Kiyomizu-Gegend — ~260 Y","30 Min.","BABY SCHLAEFT IM BUGGY: Kurzschlaf"],
      ["09:00–10:30","Kiyomizu-dera (778 n.Chr.) + Sannenzaka/Ninenzaka-Gassen — 500 Y","90 Min.","Noch vor den groessten Massen; Matcha-Eis-Gassen; Yasaka Pagoda Fotomotiv"],
      ["10:30–11:30","Rihga Royal Fruehstueck (spaeter, nach fruehm Start) — inkl.","60 Min.","Zurueck zum Hotel, durchatmen"],
      ["11:30–13:00","Bus/Taxi zu Kinkaku-ji (Goldener Pavillon) — 500 Y","90 Min.","30–45 Min. besuchen reicht; ikonisch; Garten schoen"],
      ["13:00–14:00","Mittagessen Kinkaku-ji Naehe — ~1.000–1.500 Y","60 Min.",""],
      ["14:00–15:30","Bus/Taxi zurueck — BABY SCHLAEFT IM BUGGY (Mittagsschlaf)","90 Min.",""],
      ["15:30–17:30","Baby Mittagsschlaf + Ruhe","120 Min.",""],
      ["18:00–20:00","Gion Abendspaziergang + Dinner: Hanamikoji, Machiya-Haeuser — kostenlos","120 Min.","ACHTUNG (Lena): Gion-Laeden mittags zu — abends ist die richtige Zeit"],
    ],
    info:["Verdichtet: Fushimi (frueh) + Kiyomizu + Kinkaku an einem Tag — alle drei sind Frueh-/Vormittags-tauglich","Fushimi: nach 30 Min. aufwaerts werden die Massen merklich weniger","Diese Verdichtung schafft Platz fuer den Hiroshima-Tag"]},

  { nr:15, datum:"Mi 16.9.", ort:"Kyoto", strecke:"Kyoto → Kyoto", hotel:"Rihga Royal Hotel Kyoto",
    top3:["⭐ Philosophenweg (2km Kanal-Spazierweg) — kostenlos","Honen-in Tempel (Moos, Reetdach, Sandgaerten) — kostenlos (GEHEIMTIPP!)","Eikando Tempelgarten — 600 Y + Nanzen-ji Aquadukt — kostenlos"],
    ablauf:[
      ["08:00–09:00","Rihga Royal Fruehstueck (sehr gut, inkl.)","60 Min.",""],
      ["09:00–09:30","Bus zu Nanzen-ji/Philosophenweg — ~230 Y","30 Min.","BABY SCHLAEFT IM BUGGY: Kurzschlaf"],
      ["09:30–11:00","Philosophenweg (2km Kanal-Spazierweg) — kostenlos","90 Min.","Breiter Weg, Buggy ok; Cafes am Weg; kaum Touristen morgens"],
      ["11:00–11:45","Honen-in Tempel (GEHEIMTIPP!) — kostenlos","45 Min.","Moos, Reetdach-Tor, Sandgaerten; sehr ruhig; Kuenstler-Atmosphaere"],
      ["11:45–13:00","Eikando Tempelgarten — 600 Y","75 Min.","Holzstege, Seerosenteich, September noch gruen; sehr ruhig"],
      ["13:00–14:00","Mittagessen Philosophenweg-Cafes — ~1.000–1.500 Y","60 Min.","Baby wach: Cafe ideal zum Fuettern"],
      ["14:00–15:30","Bus/Taxi zurueck — BABY SCHLAEFT IM BUGGY (Mittagsschlaf)","90 Min.",""],
      ["15:30–17:00","Nanzen-ji (Zen-Tempel, Aquadukt) — Anlage kostenlos","90 Min.","Backsteinaquadukt mitten in Parkanlage; weitlaeufig; Buggy ok"],
      ["17:30–19:30","Kamo River Abend: Demachiyanagi + Dango — kostenlos","120 Min.","Bester Sonnenuntergangsort Kyotos"],
    ],
    info:["Philosophenweg = Pflicht mit Baby: flacher Weg, gruener Kanal, kleine Cafes","Honen-in: nicht in Standard-Reisefuehrern; einer der besten Geheimtipps Kyotos!","Eikando + Nanzen-ji + Honen-in: alle innerhalb 15 Min. Fussweg"]},

  { nr:16, datum:"Do 17.9.", ort:"Kyoto", strecke:"Kyoto → Kyoto", hotel:"Rihga Royal Hotel Kyoto",
    top3:["Arashiyama: Saga Toriimoto + Gio-ji + Otagi (Geheimtipps!) + Bambuswald","Yudofu Lunch Arashiyama (Tofu-Eintopf, Kyoto-Spezialitaet)","Uji Nachmittag: Byodoin Tempel + Matcha (20 Min. Zug)"],
    ablauf:[
      ["08:00–09:00","Rihga Royal Fruehstueck (letztes Kyoto-Fruehstueck!)","60 Min.",""],
      ["09:00–09:30","Bus/Zug zu Arashiyama — ~230–470 Y","30 Min.","BABY SCHLAEFT IM BUGGY: Kurzschlaf"],
      ["09:30–10:00","Saga Toriimoto Preserved Street (Edo-Holzhaeuser) — kostenlos","30 Min.","Kaum Touristen; alte Holzhaeuser; Buggy ok auf Strasse"],
      ["10:00–10:45","Gio-ji Tempel (GEHEIMTIPP: Moos-Garten, Maerchenwald) — 500 Y","45 Min.","Ruhig; Wege holprig → BABYTRAGE empfohlen"],
      ["10:45–11:30","Otagi Nenbutsuji (1.200 einzigartige Statuen) — 300 Y","45 Min.","Jede Statue anders; manche lustig; BABYTRAGE (Stufen)"],
      ["11:30–12:00","Sagano Bambuswald — kostenlos","30 Min.","Kurzer Stop reicht (20–30 Min.)"],
      ["12:00–13:00","Yudofu Lunch Arashiyama — ~1.500–3.000 Y","60 Min.","Sagano Tourou o.ae.; ruhig; Hochstuhl"],
      ["13:00–14:00","Zug Arashiyama → Uji — ~590 Y, ~60 Min.","60 Min.","BABY SCHLAEFT IM BUGGY: Mittagsschlaf!"],
      ["14:00–15:30","Uji: Byodoin Tempel (UNESCO, 1052) — 600 Y","90 Min.","Ruhige Stadt; Buggy ok; sehr entspannt"],
      ["15:30–16:30","Uji: Matcha-Desserts direkt aus Laeden — ~300–800 Y","60 Min.","Uji = Japans Matcha-Hauptstadt"],
      ["16:30–17:30","Zug Uji → Kyoto — ~310 Y","60 Min.",""],
      ["18:00–20:00","Letzter Kyoto-Abend: Pontocho Dinner — ~2.000–4.000 Y","120 Min.","Koffer packen — morgen weiter nach Izu/Ito"],
    ],
    info:["Gio-ji + Otagi Nenbutsuji: die besten Geheimtipps Arashiyamas; kaum in Standard-Reisefuehrern","Arashiyama → Uji zeitlich gut: Gesamt-Bahnkosten ~1.800 Y/Person; sehr abwechslungsreich","Uji statt Nara: ruhiger, weniger touristisch, mit Baby entspannter (Nara gestrichen)"]},

  { nr:17, datum:"Fr 18.9.", ort:"Ito (Izu)", strecke:"Kyoto → Ito", hotel:"Ito Ryokan/Hotel (noch buchen!)",
    top3:["Shinkansen Kyoto → Atami (~1 Std. 45 Min.) — ~7.500 Y/Person","Izu Kyuko Linie Atami → Ito (~25 Min.) — ~370 Y/Person","Ankunft fruehe Nachmittag: Check-in, Hafen, Onsen"],
    ablauf:[
      ["08:00–09:00","Rihga Royal letztes Fruehstueck (inkl., sehr gut!)","60 Min.",""],
      ["09:00–09:30","Checkout, Gepaeck, zu Kyoto Station","30 Min.",""],
      ["09:45–11:30","Shinkansen Kyoto → Atami (Hikari/Kodama) — ~7.500 Y/Person","105 Min.","BABY SCHLAEFT IM BUGGY: Mittagsschlaf-Slot im Zug"],
      ["11:30–12:00","Umstieg Atami: Izu Kyuko Linie nach Ito — ~370 Y/Person","30 Min.",""],
      ["12:00–12:25","Izu Kyuko Linie Atami → Ito","25 Min.","Kuestenstrecke; schoene Meerblicke"],
      ["12:30–14:00","Check-in Ryokan/Hotel Ito + Mittagessen","90 Min.","Babybett bestaetigt?"],
      ["14:00–15:30","Baby-Mittagsschlaf + Ankommen","90 Min.",""],
      ["15:30–17:00","Ito Hafen: Fischmarkt, Spaziergang Uferpromenade — kostenlos","90 Min.","Ruhige Hafenstadt; ganz anderes Tempo als Osaka/Kyoto"],
      ["17:00–18:30","Onsen im Ryokan (privater Raum, ruhig)","90 Min.",""],
      ["18:30–20:30","Dinner: frischer Kinmedai (Goldbarsch, Ito-Spezialitaet) am Hafen — ~1.500–2.500 Y","120 Min.",""],
    ],
    info:["Ito statt Shimoda gewaehlt: Shimoda hat schoenere Straende, aber 3 Std. Rueckweg nach Tokio — mit Baby zu lang. Ito ist 1,5 Std. von Tokio entfernt","Geografie: Izu liegt suedlich von Hakone/Tokio — von Kyoto fahrt ihr erst Richtung Osten zurueck, dann sued zur Halbinsel; Izu passt gut als Natur-Abschluss vor dem Rueckflug"]},

  { nr:18, datum:"Sa 19.9.", ort:"Ito (Izu)", strecke:"Ito → Ito", hotel:"Ito Ryokan/Hotel (noch buchen!)",
    top3:["⭐ Jogasaki-Kueste: Kadowaki Haengebruecke (48m, 23m ueber dem Meer) — kostenlos","Cliff Walk auf Vulkanklippen (Babytrage!) — kostenlos","Ito Kogen Lunch + Onsen-Abschied"],
    ablauf:[
      ["08:30–09:00","Ryokan-Fruehstueck (traditionell, inkl.)","30 Min.",""],
      ["09:00–09:20","Bus/Taxi zur Jogasaki-Kueste — ~300–500 Y","20 Min.","BABY SCHLAEFT IM BUGGY: Kurzschlaf"],
      ["09:20–11:30","Jogasaki-Kueste: Kadowaki Haengebruecke + Cliff Walk Nordabschnitt — kostenlos","130 Min.","BABYTRAGE statt Buggy (Felsenpfad); morgens kaum Touristen; nur Nordabschnitt, nicht volle 9km-Route"],
      ["11:30–12:30","Mittagessen Ito Kogen (Bergplateau-Restaurant, Meerblick) — ~1.500 Y","60 Min.",""],
      ["12:30–13:00","Rueckfahrt nach Ito","30 Min.","Baby schlaeeft"],
      ["13:00–14:30","Baby-Mittagsschlaf Ryokan","90 Min.",""],
      ["14:30–16:00","Ito Hafen: Fischmarkt, Austernbar direkt am Wasser — ~500–1.500 Y","90 Min.",""],
      ["16:00–17:30","Onsen im Ryokan (Abschieds-Onsen)","90 Min.",""],
      ["17:30–19:30","Dinner Ryokan oder Fischrestaurant am Hafen — ~2.000–3.000 Y","120 Min.","Letzter ruhiger Abend vor Tokio"],
    ],
    info:["Jogasaki-Kueste: dramatische Vulkanklippen, einer der schoensten Kuestenabschnitte Japans, kaum Touristen verglichen mit Kyoto/Osaka","Nur den Nordabschnitt (Kadowaki-Bruecke + 2-3km) machen — volle Route ist 9km und zu lang mit Baby"]},

  { nr:19, datum:"So 20.9.", ort:"Tokio", strecke:"Ito → Tokio", hotel:"Tokio 2 Airbnb (noch buchen — Narita-Anbindung!)",
    top3:["Izu Kyuko + Shinkansen Ito → Tokio (~1,5 Std.) — ~6.500 Y/Person","⭐ TeamLab Planets (digitale Kunst) — Ticket VORAB! ~3.200 Y (~17,50 €)","Check-in neues Tokio-Airbnb"],
    ablauf:[
      ["08:30–09:00","Ryokan-Fruehstueck (letztes Mal)","30 Min.",""],
      ["09:00–09:30","Checkout, Gepaeck, zu Ito Station","30 Min.",""],
      ["09:30–10:00","Izu Kyuko Linie Ito → Atami — ~370 Y","30 Min.",""],
      ["10:15–11:10","Shinkansen Atami → Tokyo — ~5.500–6.500 Y/Person","55 Min.","BABY SCHLAEFT IM BUGGY: Kurzschlaf im Zug"],
      ["11:30–13:00","Ankunft Tokyo, Check-in Airbnb + Mittagessen","90 Min.","Babybett bestaetigt?"],
      ["13:00–14:30","Baby-Mittagsschlaf (falls noetig)","90 Min.",""],
      ["14:30–17:00","TeamLab Planets (digitale Kunst, immersiv) — 3.200 Y (Ticket VORAB!)","150 Min.","Baby: Helle Lichter faszinierend; Wasserbereiche — Baby besser draussen lassen oder Trage; Planets schliesst Ende 2027!"],
      ["18:00–19:30","Dinner + Tokio Bierbar (Empfehlung Lena: Shimokitazawa oder Golden Gai)","90 Min.","Erster von zwei Tokio-Abenden zum Abschluss"],
    ],
    info:["TeamLab Planets: Tickets unbedingt vorab online buchen (oft ausverkauft)! teamlab.art — schliesst Ende 2027, 2026 ist letztes volles Jahr","TeamLab Borderless (Azabudai Hills) waere ein zweites, anderes Erlebnis — falls Zeit, in einen der fruehen Tokio-1-Tage einbauen","Tokio-2-Unterkunft: auf gute Narita-Anbindung achten (Ueno/Asakusa ideal: Keisei Skyliner 41 Min.)"]},

  { nr:20, datum:"Mo 21.9.", ort:"Tokio", strecke:"Kaiserpalast + Ginza + Ueno/Akihabara", hotel:"Tokio 2 Airbnb (noch buchen — Narita-Anbindung!)",
    top3:["Kaiserpalast-Ostgaerten (Higashi-Gyoen) + Marunouchi/Tokyo Station — kostenlos","Ginza: Itoya, Uniqlo + GU Flagship, Ginza Six Dachgarten, Depachika","Ueno Park + Ameyoko-Markt + Akihabara (Manga, Anime) am Nachmittag"],
    ablauf:[
      ["08:00–08:45","Fruehstueck Airbnb (Kueche nutzen!)","45 Min.",""],
      ["08:45–09:15","U-Bahn zum Kaiserpalast / Tokyo Station","30 Min.","BABY SCHLAEFT IM BUGGY: Kurzschlaf"],
      ["09:15–10:45","Kaiserpalast-Ostgaerten (Higashi-Gyoen, weitlaeufig, gruen) — kostenlos","90 Min.","Palast selbst nicht zugaenglich, aber Ostgaerten ruhig + schoen; Buggy ideal"],
      ["10:45–11:15","Marunouchi: historische rote Backstein-Tokyo-Station + Architektur — kostenlos","30 Min.","Eindrucksvolle Fassade; KITTE-Mall mit Dachterrasse (Blick auf Station)"],
      ["11:15–13:00","Ginza: Chuo-dori, Itoya (12 Etagen Schreibwaren), Uniqlo + GU Flagship — kostenlos/Shopping","105 Min.","Tokios edelstes Viertel; Itoya = Papier-Paradies; groesste Uniqlo der Welt; Tax-Free"],
      ["13:00–14:00","Mittagessen Ginza: Depachika (Mitsukoshi/Matsuya) oder Restaurant — ~1.500–2.500 Y","60 Min.","HITZE-SCHUTZ: klimatisierte Kaufhaeuser; Ginza Six Dachgarten kostenlos"],
      ["14:00–15:30","U-Bahn nach Ueno — BABY SCHLAEFT IM BUGGY (Mittagsschlaf)","90 Min.","BABY SCHLAEFT IM BUGGY: Transfer = Mittagsschlaf"],
      ["15:30–16:45","Ueno Park (Museen, Teich, Tempel) + Ameyoko-Markt (lebhafte Marktstrasse) — Park kostenlos","75 Min.","Ameyoko: voll, bunt, Street Food, guenstig; Ueno Park weitlaeufig fuer Buggy"],
      ["16:45–18:30","Akihabara (Manga, Anime, Retro-Games, Electronics) — kostenlos","105 Min.","2 Stationen von Ueno; Mandarake (Manga), Super Potato (Retro-Games), Anime-Stores; sehr lebhaft"],
      ["18:30–20:00","Dinner Akihabara/Ueno + letzter Bierbar-Abend — ~2.000–3.000 Y","90 Min.","Letzter voller Abend; Izakaya unter den Bahngleisen (Okachimachi) sehr stimmungsvoll"],
      ["20:00–20:40","Heimfahrt zur Unterkunft","40 Min.","BABY SCHLAEFT IM BUGGY"],
    ],
    info:["Kaiserpalast: nur Ostgaerten zugaenglich (kostenlos, Mo+Fr teils geschlossen — Mo 21.9. PRUEFEN, ggf. nur Aussenanlage + Nijubashi-Bruecke)","Akihabara + Ueno liegen 2 Yamanote-Stationen auseinander — idealer kombinierter Nachmittag","Ginza Itoya: 12 Etagen Papier/Stifte/Kalligrafie; Uniqlo Ginza = groesste Filiale weltweit (12 Etagen)"]},

  { nr:21, datum:"Di 22.9.", ort:"Tokio → Narita", strecke:"Tokio → Narita", hotel:"—",
    top3:["Entspannter letzter Vormittag nahe Unterkunft / Viertel-Bummel","Last-Minute Shopping: Adidas Japan, Uniqlo/GU, Matsumoto Kiyoshi","Abflug 22:30 Uhr Narita (Keisei Skyliner ab Ueno ~41 Min.)"],
    ablauf:[
      ["08:00–09:00","Fruehstueck Airbnb (in Ruhe, Kueche nutzen)","60 Min.","Kein Hetzen am letzten Tag"],
      ["09:00–11:00","Entspannter Viertel-Bummel nahe Unterkunft ODER ein noch offener Wunschpunkt","120 Min.","Bewusst ruhig — Asakusa schon an Tag 2 gemacht, hier kein zweiter Besuch noetig"],
      ["11:00–13:00","Last-Minute Shopping: Adidas Japan-Exklusiv-Shirts, Uniqlo/GU, Matsumoto Kiyoshi (Kosmetik, Baby)","120 Min.","Tax-Free direkt im Laden mit Reisepass — kein extra Schritt am Flughafen noetig"],
      ["13:00–14:00","Letztes Mittagessen Japan — ~1.500 Y","60 Min.",""],
      ["14:00–16:00","Baby Mittagsschlaf (KRITISCH — langer Flugtag!) + Koffer endgueltig packen","120 Min.","Baby ausgeruht fuer Flug"],
      ["16:00–17:00","Airbnb-Checkout, Gepaeck","60 Min.","Gepaeck ggf. vormittags schon einlagern"],
      ["17:00–18:00","Keisei Skyliner ab Ueno → Narita (~41 Min., ~2.520 Y/Person)","60 Min.","Schnellste + entspannteste Variante; Alternative Taxi ~20.000 Y"],
      ["18:00–22:00","Narita: Check-in, Security, Duty Free, letztes Japan-Dinner","240 Min.","Whisky (Nikka, Suntory), Matcha, Kosmetik guenstig im Duty Free"],
      ["22:30","Abflug Narita → Frankfurt (via Dubai)","—","Sayonara Japan!"],
    ],
    info:["Keisei Skyliner ab Ueno: ~2.520 Y/Person, 41 Min. — schnellste Anbindung; deshalb Tokio-2-Airbnb idealerweise Ueno/Asakusa-Naehe","Kein Asakusa mehr am Abreisetag (bereits Tag 2 gemacht) — letzter Tag bewusst entspannt","Duty Free Narita: Japanischer Whisky erheblich guenstiger als in Europa"]},
];

export const HOTELS = [
  { s:"Tokio 1",  n:"Airbnb Chitose 3-8-6, Sumida Ward (bei Morishita Station)", d:"3.–8.9.",  nt:5, k:"368 €",  b:"ok",  st:"gebucht ✓ — 74 € bezahlt, 294 € am 18.08.", sto:"stornierbar bis 08.08.", bb:"bestaetigen" },
  { s:"Hakone",   n:"Ryokan Gora: Yunosumika / Setsugetsuka / Ajisai",      d:"8.–10.9.", nt:2, k:"~200–350 €",b:"todo",  st:"noch buchen!",              sto:"—",         bb:"bestaetigen" },
  { s:"Osaka",    n:"Airbnb: 3 Min. zu Fuss zum Bahnhof, Namba 3 Min. Zug — 4,89★", d:"10.–13.9.", nt:3, k:"~180 €", b:"ok", st:"gebucht ✓ — Umbuchung auf 3N bestaetigt", sto:"kostenlos bis 05.09.", bb:"bestaetigen" },
  { s:"Kyoto",    n:"Rihga Royal Hotel Kyoto",                              d:"13.–18.9.",nt:5, k:"450 €",      b:"warn",  st:"bezahlt — Datum auf 13.9. aendern! (anrufen)", sto:"bis 05.09.", bb:"anfragen" },
  { s:"Ito (Izu)",n:"Ryokan/Hotel Ito — noch auswaehlen (Jogasaki-Kueste in der Naehe)", d:"18.–20.9.",nt:2, k:"~250–400 €", b:"todo", st:"noch buchen!", sto:"—", bb:"bestaetigen" },
  { s:"Tokio 2",  n:"Airbnb: Kueche + sep. Schlafzimmer, Narita-Anbindung wichtig (Ueno/Asakusa ideal)", d:"20.–22.9.",nt:2, k:"~180–240 €",  b:"todo",  st:"noch buchen!",              sto:"—",         bb:"Pflicht" },
] as const;

export const TODOS = {
  kritisch: [
    { t:"Tokio 1 Airbnb: 294 € werden am 18.08. abgebucht (Saldo nach 74 € Anzahlung)", f:"bis 18.08." },
    { t:"Hakone Gora-Ryokan buchen (2 Naechte 8.–10.9.!): Yunosumika / Setsugetsuka / Ajisai", f:"sofort" },
    { t:"Osaka Airbnb (3N bestaetigt): Zahlung am 28.08. via Visa", f:"bis 28.08." },
    { t:"Kyoto Rihga Royal: Check-in auf 13.9. aendern (NICHT 14./15.9.!) — anrufen! (bereits bezahlt)", f:"bis 05.09." },
    { t:"Ito Ryokan/Hotel buchen (2 Naechte 18.–20.9., nahe Jogasaki-Kueste)", f:"bald" },
    { t:"Tokio 2 Airbnb buchen — 2 Naechte (20.–22.9.), Kueche + sep. Schlafzimmer, gute Narita-Anbindung (Ueno/Asakusa)", f:"bald" },
  ],
  wichtig: [
    { t:"TeamLab Planets Tokyo: Ticket VORAB online buchen! Oft ausverkauft. teamlab.art" },
    { t:"Tokyo Skytree Sonnenuntergang: Ticket via GetYourGuide (Lena: vor dem Slot rein, laenger bleiben)" },
    { t:"Hakone: Ryokan auswaehlen + Baby-Onsen-Eignung direkt beim Haus erfragen" },
    { t:"Hakone: Allergien + Babybett fuer Kaiseki-Dinner vorab anmelden" },
    { t:"Babybett bei ALLEN Unterkuenften schriftlich bestaetigen" },
    { t:"Romancecar reservieren: Shinjuku → Hakone 8.9. (odakyu.jp)" },
  ],
  empfohlen: [
    { t:"Suica DIGITAL ins iPhone Wallet (kein Flughafen noetig): Mastercard/Amex zum Aufladen (Visa wird oft abgelehnt!); digital NICHT vorab voll laden (kein Bar-Refund) — in 5.000er-Schritten" },
    { t:"eSIM 30GB+ vorab kaufen: Ubigi (Docomo, beste Abdeckung) oder Journey Japan unlimited — aktiviert sich bei Ankunft" },
    { t:"Hakone Freepass 2-Tage: digital kaufen (odakyu.jp)" },
    { t:"Shibuya Sky Tickets: 2–4 Wochen vorher (Empfehlung Michelle); oder kostenlose Mexikaner-Hack-Aussicht (Cielito Lindo) auf Shibuya Crossing" },
    { t:"Uniqlo + GU Flagship-Stores: Ginza, Shinsaibashi (Osaka), Shibuya — Tax-Free direkt im Laden mit Reisepass" },
    { t:"Adidas Japan: Exklusiv-T-Shirts/Designs, nicht ueberall sonst erhaeltlich" },
    { t:"Kaiseki-Dinner Kyoto (letzter Abend falls gewuenscht): vorab reservieren" },
    { t:"Reisekrankenversicherung: Baby explizit mitversichert?" },
    { t:"Reisepass Baby: gueltig? Kinderreisepass seit 01.01.2024 abgeschafft!" },
  ],
  besprechen: [
    { t:"TeamLab Borderless (Azabudai Hills) zusaetzlich zu Planets? Eher in Tokio-1-Optionstage einbauen" },
    { t:"Fuji-Region (Kawaguchiko): Tagesausflug ab Tokio anstelle eines offenen Tages? Noch offen" },
    { t:"Miyajima/Hiroshima: bewusst NICHT eingeplant (Entscheidung gefallen)" },
  ],
} as const;

export const PACKING = {
  baby: [
    { t: "Viel Babynahrung & Praemilch", note: "In Japan kaum ohne Salz/Zucker erhaeltlich und teuer (Tipp Isabelle) — fuer die erste Reisehaelfte einpacken" },
    { t: "Waschtuecher von Dr. Beckmann" },
    { t: "Babytrage + leichter Buggy", note: "Trage fuer Treppen/holprige Wege: Gio-ji, Otagi, Fushimi oben, Higashiyama-Gassen" },
    { t: "Windel-Vorrat fuer die ersten Tage" },
    { t: "Sonnenschutz Baby", note: "Anfang Sept. heiss/schwuel — Sonnenhut, leichte Decke fuer Buggy" },
  ],
  strategie: [
    { t: "Sehr wenig Gepaeck — bewusst leicht reisen" },
    { t: "Notgepaeck griffbereit im Handgepaeck", note: "Wechselkleidung Baby + Eltern, Windeln, etwas Babynahrung — falls Hauptkoffer per Takkyubin getrennt unterwegs ist" },
  ],
  offen: [
    { t: "Weitere Punkte folgen — Liste wird laufend ergaenzt" },
  ],
} as const;
